export const PRESET_THEMES = [
  {
    name: 'Quantum Slate (Default)',
    description: 'Sleek enterprise dark/light tech theme with deep slate and active blue accents.',
    theme_class: 'theme-quantum',
    font_family_heading: 'Inter',
    font_family_body: 'Outfit',
    color_primary: '#0f172a',
    color_secondary: '#3b82f6',
    color_bg_light: '#ffffff',
    color_bg_dark: '#0f172a',
    color_text_light: '#1e293b',
    color_text_dark: '#f8fafc',
    color_accent: '#f59e0b',
    border_radius: 8
  },
  {
    name: 'Aurora Borealis',
    description: 'Vibrant deep-space theme with neon greens, cosmic purples, and glassmorphism.',
    theme_class: 'theme-aurora',
    font_family_heading: 'Space Grotesk',
    font_family_body: 'DM Sans',
    color_primary: '#020617',
    color_secondary: '#22d3ee',
    color_bg_light: '#f0fdfa',
    color_bg_dark: '#020617',
    color_text_light: '#134e4a',
    color_text_dark: '#ccfbf1',
    color_accent: '#a855f7',
    border_radius: 16
  },
  {
    name: 'Sunset Gradient',
    description: 'Warm sunset palette with coral, rose, and amber tones for a creative studio feel.',
    theme_class: 'theme-sunset',
    font_family_heading: 'Sora',
    font_family_body: 'Plus Jakarta Sans',
    color_primary: '#1c1917',
    color_secondary: '#f43f5e',
    color_bg_light: '#fffbeb',
    color_bg_dark: '#1c1917',
    color_text_light: '#292524',
    color_text_dark: '#fef3c7',
    color_accent: '#fb923c',
    border_radius: 12
  },
  {
    name: 'Ocean Depths',
    description: 'Deep ocean blues and teals with a serene, professional financial vibe.',
    theme_class: 'theme-ocean',
    font_family_heading: 'Instrument Sans',
    font_family_body: 'Inter',
    color_primary: '#0c4a6e',
    color_secondary: '#0ea5e9',
    color_bg_light: '#f0f9ff',
    color_bg_dark: '#0c4a6e',
    color_text_light: '#0c4a6e',
    color_text_dark: '#e0f2fe',
    color_accent: '#06b6d4',
    border_radius: 6
  },
  {
    name: 'Cyberpunk Neon',
    description: 'Electric neon pinks, cyan, and dark grid backgrounds for cutting-edge tech brands.',
    theme_class: 'theme-cyberpunk',
    font_family_heading: 'Rajdhani',
    font_family_body: 'Exo 2',
    color_primary: '#0a0a0a',
    color_secondary: '#ec4899',
    color_bg_light: '#fdf2f8',
    color_bg_dark: '#0a0a0a',
    color_text_light: '#171717',
    color_text_dark: '#fce7f3',
    color_accent: '#06b6d4',
    border_radius: 4
  },
  {
    name: 'Forest Canopy',
    description: 'Organic greens, warm browns, and earthy neutrals for eco-conscious and nature brands.',
    theme_class: 'theme-forest',
    font_family_heading: 'Playfair Display',
    font_family_body: 'Source Sans 3',
    color_primary: '#14532d',
    color_secondary: '#16a34a',
    color_bg_light: '#f0fdf4',
    color_bg_dark: '#14532d',
    color_text_light: '#14532d',
    color_text_dark: '#dcfce7',
    color_accent: '#ca8a04',
    border_radius: 10
  }
];

// Component Palette — all available section types
export const COMPONENT_PALETTE = [
  { category: 'Content', items: [
    { type: 'builtin', id: 'hero', name: 'Hero Banner', icon: '🎯', desc: 'Full-width hero section' },
    { type: 'builtin', id: 'intro', name: 'About / Intro', icon: '📋', desc: 'Company introduction block' },
    { type: 'builtin', id: 'services', name: 'Services Grid', icon: '⚙️', desc: 'Service cards grid' },
    { type: 'builtin', id: 'projects', name: 'Portfolio Showcase', icon: '🖼️', desc: 'Featured projects gallery' },
    { type: 'builtin', id: 'testimonials', name: 'Testimonials', icon: '💬', desc: 'Client testimonials carousel' },
    { type: 'builtin', id: 'process', name: 'Work Process', icon: '🔄', desc: 'Step-by-step process flow' },
    { type: 'builtin', id: 'tech_stack', name: 'Tech Stack', icon: '🛠️', desc: 'Technology icons grid' },
    { type: 'builtin', id: 'why_us', name: 'Why Choose Us', icon: '✅', desc: 'Key differentiators section' },
    { type: 'builtin', id: 'github', name: 'GitHub Repos', icon: '🐙', desc: 'Open source repository cards' },
    { type: 'builtin', id: 'trusted_by', name: 'Trusted By', icon: '🏢', desc: 'Client logos marquee' },
    { type: 'builtin', id: 'cta_block', name: 'Call to Action', icon: '📣', desc: 'CTA with action buttons' },
    { type: 'builtin', id: 'contact', name: 'Contact Form', icon: '✉️', desc: 'Contact form with estimator' },
  ]},
  { category: 'Custom', items: [
    { type: 'custom_html', id: 'custom_html', name: 'Custom HTML Block', icon: '🧩', desc: 'Write custom HTML/CSS/JS' },
    { type: 'custom_html', id: 'spacer', name: 'Spacer / Divider', icon: '➖', desc: 'Empty space or decorative line' },
    { type: 'custom_html', id: 'embed', name: 'Embed Block', icon: '📺', desc: 'Iframe, video, or widget embed' },
    { type: 'custom_html', id: 'rich_text', name: 'Rich Text Block', icon: '📝', desc: 'Formatted text content' },
  ]},
  { category: 'AI Generated', items: [
    { type: 'ai', id: 'ai_hero', name: 'AI Hero Banner', icon: '✨', desc: 'Generate hero with AI' },
    { type: 'ai', id: 'ai_pricing', name: 'AI Pricing Table', icon: '✨', desc: 'Generate pricing section' },
    { type: 'ai', id: 'ai_faq', name: 'AI FAQ Section', icon: '✨', desc: 'Generate FAQ accordion' },
    { type: 'ai', id: 'ai_testimonials', name: 'AI Testimonials', icon: '✨', desc: 'Generate testimonial cards' },
    { type: 'ai', id: 'ai_cta', name: 'AI Call to Action', icon: '✨', desc: 'Generate CTA block' },
    { type: 'ai', id: 'ai_features', name: 'AI Features Grid', icon: '✨', desc: 'Generate features section' },
    { type: 'ai', id: 'ai_stats', name: 'AI Stats Counter', icon: '✨', desc: 'Generate statistics section' },
    { type: 'ai', id: 'ai_team', name: 'AI Team Section', icon: '✨', desc: 'Generate team members' },
  ]}
];
